{
 "title": "Order Service Observability",
 "tags": [
  "order-service",
  "observability"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total[1m])",
     "legendFormat": "{{method}} {{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Request Duration (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p50 - {{method}} {{path}}"
    },
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p95 - {{method}} {{path}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p99 - {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Total Orders Created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "orders_created_total" }
   ]
  },
  {
   "title": "Total Orders Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(orders_failed_total)" }
   ]
  },
  {
   "title": "Failed Orders by Reason",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "targets": [
    { "expr": "orders_failed_total", "legendFormat": "{{reason}}" }
   ]
  },
  {
   "title": "Median Order Value",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(order_value_dollars_bucket[5m]))",
     "legendFormat": "Median Order Value"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{status_code=\"2xx\"}[1m])",
     "legendFormat": "2xx - {{method}} {{path}}"
    },
    {
     "expr": "rate(http_requests_total{status_code=\"4xx\"}[1m])",
     "legendFormat": "4xx - {{method}} {{path}}"
    },
    {
     "expr": "rate(http_requests_total{status_code=\"5xx\"}[1m])",
     "legendFormat": "5xx - {{method}} {{path}}"
    }
   ]
  }
 ]
}